### PR TITLE
fix: decorator_call_expression type arguments

### LINKED ISSUE #283: bug: highlight broken with decorators
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.20.8

### Describe the bug

When you specify generic type in decorator, it's break the highlight of code below

Broken
image

Normal
image

### Steps To Reproduce/Bad Parse Tree

1. Create a calss
2. Declare a method in this class
3. Decorate this method
4. Pass generic type in decorator

### Expected Behavior/Parse Tree

Syntax highlight will work well

### Repro

```TypeScript
function system<A>(...args: any): any {}

export default class bSrchCard   {
	@system()
	override readonly analyticsParams = {};

	@system()
	override readonly analyticsOptions = {};
}
```

### PR DESCRIPTION
**Pull request by nohehf**
This fixes #283, I added a test case for what was failing before, that now passes.

### CODE REVIEW

**Comment by nohehf** [comment]
I did not realise that the parser was this long, maybe it should not be included in the PR, let me know what you think.

**Comment by nohehf** [comment]
@amaanq could you review this one please ?

**Comment by nohehf** [comment]
@hendrikvanantwerpen maybe ? (sorry to disturb if I do, I just feel like it could be nice to fix this)

**Comment by amaanq** [comment]
yeah sorry for the delay @nohehf, but thanks for the PR!

**Comment by nohehf** [comment]
Thanks for merging @amaanq (and thanks for the review @hendrikvanantwerpen) !

**Pull request merged**
