### PR TITLE
Don't generate node and rust bindings in subfolders tsx/ and typescript/

### PR DESCRIPTION
**Pull request by mjambon**
Without this, the following extra files get generated when we run `npm run build`:
```
	tsx/Cargo.toml
	tsx/binding.gyp
	tsx/bindings/
	typescript/Cargo.toml
	typescript/binding.gyp
	typescript/bindings/
```
Files with such names already exist under the project's root e.g. https://github.com/tree-sitter/tree-sitter-typescript/blob/master/Cargo.toml.

I don't know what these files are for so I don't know if this PR does the right thing :-). Maybe the right behavior is instead to keep those under `tsx/` and `typescript/` and delete the ones under the project root?

Checklist:
- [x] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by mjambon** [comment]
The question about these new generated files was asked in https://github.com/tree-sitter/tree-sitter-typescript/pull/135 and https://github.com/tree-sitter/tree-sitter-typescript/pull/163

**Review by dcreager — APPROVED** [review]
:+1: _For this particular repo_, this is absolutely the right thing to do, because we already have these bindings files in the repo root.  So the new files being generated in the `tsx` and `typescript` directories are redundant with the files that already exist.

(The `Cargo.toml` is needed to publish the [Rust crate](https://crates.io/crates/tree-sitter-typescript) for this parser, `binding.gyp` is for the npm package, and the `bindings/{node,rust}` directories contain their implementations.)

**Comment by resolritter** [comment]
FWIW when I tried to use `--no-bindings` locally on https://github.com/tree-sitter/tree-sitter-typescript/pull/135, I got the following:

```
> ../node_modules/.bin/tree-sitter generate --no-bindings
error: Found argument '--no-bindings' which wasn't expected, or isn't valid in this context

USAGE:
    tree-sitter generate [FLAGS] [OPTIONS] [grammar-path]

For more information try --help

> ../node_modules/.bin/tree-sitter --version
tree-sitter 0.19.2 (d037c4914d7845385dbf330f1a653777f81b7240)
```

**Comment by mjambon** [comment]
@resolritter ah, that's good to know.

Here's the relevant section from tree-sitter's git log:
```
commit 24785cdb39ad2740ca33c111490984333787f5d3
Author: Max Brunsfeld <maxbrunsfeld@gmail.com>
Date:   Mon Mar 8 16:36:59 2021 -0800

    0.19.3

commit 9e50befcf8e1b6855337b7a877aa3099947f5678
Author: Max Brunsfeld <maxbrunsfeld@gmail.com>
Date:   Mon Mar 8 12:02:01 2021 -0800

    For node-types.json, process supertypes in a stable order

commit 8e894ff3f1898fcaa09ae125bbd5fde8467aea42
Author: Max Brunsfeld <maxbrunsfeld@gmail.com>
Date:   Mon Mar 8 12:01:45 2021 -0800

    Add --no-bindings flag to generate subcommand

```

So we need to set a constraint on tree-sitter >= 0.19.3.

**Comment by mjambon** [comment]
I added a version constraint and also added the unwanted files to `.gitignore` as a precaution. Thanks @dcreager and @resolritter for your help.

**Pull request merged**
