### PR TITLE
Parse type-only exports

### PR DESCRIPTION
**Pull request by nbrahms**
Added in typescript 3.8:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html.

### CODE REVIEW

**Review by mjambon — APPROVED** [review]
Looks good to me. We need to figure out the CI failures.

**Comment by mjambon** [comment]
@patrickt this repo has both Appveyor and GitHub Actions configs. It looks like the GitHub Actions job didn't kick in, and the Appveyor job failed.

**Comment by nbrahms** [comment]
My local `node-gyp rebuild` output seems reasonable:

```
✗ npx node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.11.0 | darwin | x64
gyp info find Python using Python version 3.9.2 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/nbrahms/dev/tree-sitter-typescript/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/nbrahms/Library/Caches/node-gyp/15.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/nbrahms/Library/Caches/node-gyp/15.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/nbrahms/Library/Caches/node-gyp/15.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/nbrahms/dev/tree-sitter-typescript',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/tree_sitter_typescript_binding/typescript/src/parser.o
  CC(target) Release/obj.target/tree_sitter_typescript_binding/typescript/src/scanner.o
  CC(target) Release/obj.target/tree_sitter_typescript_binding/tsx/src/parser.o
  CC(target) Release/obj.target/tree_sitter_typescript_binding/tsx/src/scanner.o
  CXX(target) Release/obj.target/tree_sitter_typescript_binding/bindings/node/binding.o
  SOLINK_MODULE(target) Release/tree_sitter_typescript_binding.node
gyp info ok
```

**Comment by nbrahms** [comment]
@maxbrunsfeld It appears that AppVeyor's `npm install` may have been broken in this commit: 892494ddbd7ed7b1737140e189aa9f0e9d0d2189. Any thoughts on how to repair the build?

**Comment by maxbrunsfeld** [comment]
Yeah, I'll take a look at that, unless anyone else gets to it first, but in the meantie, I think it's ok to merge PRs regardless of the Appveyor status, as long as we can get the other CI build running properly.

**Comment by patrickt** [comment]
@nbrahms @maxbrunsfeld I’ve disabled the Appveyor and Travis webhooks and will get a PR out to test Windows support on GHA. Gonna merge this in the meantime.

**Pull request merged**
