### PR TITLE
Separate TypeScript and TSX grammars to avoid ambiguity and support type arguments in TSX

### PR DESCRIPTION
**Pull request by nathansobo**
🍐'd with @as-cii

TSX and TypeScript are actually two slightly different languages. TypeScript includes syntax for type assertions that conflicts with JSX elements, so in TSX the type assertion syntax is not used. Previously, we handled this by just allowing the grammar to be ambiguous with respect to type assertions versus JSX expressions, but adding support for type arguments led to complications with that approach.

This PR splits the previous grammar into two separate grammars, one for Typescript and one for TSX. Now, when using this module, you need to specify the dialect when requiring as follows:

```js
const ts = require("tree-sitter-typescript/typescript");
const tsx = require("tree-sitter-typescript/tsx");
```

In order to avoid ambiguity around the special `tree-sitter` fields in the `package.json`, there is no longer a default export. Each dialect-specific subfolder includes its own `package.json` with the custom `tree-sitter` fields in it. @maxbrunsfeld I'm not sure how you're consuming these fields in other components, so let me know if this makes sense.

Duplication between grammars is minimized by a JS helper function at the root of the repo called `defineGrammar`, which takes a `dialect` argument to conditionally define the expression rule. In TypeScript, we include type assertions and filter out JSX expressions inherited from the JS grammar. In JSX, we do the opposite. We don't conditionally filter the `conflicts` to exclude JSX-related rules in the TypeScript grammar because we're assuming that conflicts that reference rules that aren't used end up being ignored. @maxbrunsfeld, is that assumption correct?

To avoid duplication of the custom scanner code, we use a simple `#include` macro in the TSX scanner to include the scanner code from the TypeScript grammar. A little gross, but gets the job done.

Our biggest concern is duplication in the tests. They *are* slightly different due to the differences in grammars explained above, but largely duplicated. I could see potentially cutting down the TSX tests to the bare minimum since we define both grammars via a shared function anyways. Let me know if that makes sense and I'll do it.

### CODE REVIEW

**Comment by nathansobo** [comment]
@maxbrunsfeld I named the common file `scanner.h` because it felt like that naming convention is used for files meant to be included elsewhere. Considering the only definitions in the file are `static`, that seemed reasonable, but I'm not very familiar with C naming conventions.

**Comment by nathansobo** [comment]
Hey @maxbrunsfeld! Got this green and addressed your concerns. My last concern is that I don't want to interfere with any other infrastructure that depends on this grammar. I moved the `tree-sitter` metadata around a bit. Will that be problematic?

**Comment by as-cii** [comment]
Thanks, @maxbrunsfeld! 🙇 

Do you mind merging this and publishing a new version? I would do it myself but I don't think I have write access to this repository.

**Comment by maxbrunsfeld** [comment]
Sorry for the delay there; I published this as 0.14.0.

**Comment by as-cii** [comment]
Thanks, Max! ❤️

**Pull request merged**
