### PR TITLE
Update the bindings

### PR DESCRIPTION
**Pull request by segevfiner**
Still need to adjust the Makefile for the C bindings, review the Rust bindings for any updates needed, and update the workflows.

# Checklist

- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Review by ObserverOfTime — COMMENTED** [review]
You should check how multi-language bindings were implemented in [xml](https://github.com/tree-sitter-grammars/tree-sitter-xml) and [markdown](https://github.com/tree-sitter-grammars/tree-sitter-markdown) (slightly different methods).

For one, the go bindings likely can't `#include` all the files due to naming conflicts.

**Comment by segevfiner** [comment]
Fixed the Go bindings...

The rest of the bindings build the grammar into a single shared library, I see no reason that it must have two separate libraries, I was able to modify the makefile to produce one?

**Comment by ObserverOfTime** [comment]
> The rest of the bindings build the grammar into a single shared library, I see no reason that it must have two separate libraries, I was able to modify the makefile to produce one...

One of the purposes of the C bindings is to build libraries that can be used in editors and Neovim for one can't load multiple languages from the same library.

**Comment by GSiesto** [comment]
As someone new to the library, I'm leveraging this thread to seek clarification.

I'm exploring the TypeScript grammar integration with Python (https://github.com/tree-sitter/py-tree-sitter) and noticed there isn't a pip package for TypeScript grammar, similar to the ones for Python grammar (https://github.com/tree-sitter/tree-sitter-python/tree/master/bindings) and JavaScript grammar (https://github.com/tree-sitter/tree-sitter-javascript/tree/master/bindings).

I am trying to avoid building the typescript library. I may have overlooked something, so I'm reaching out for clarification. Is there a reason for this?

This is especially relevant considering the deprecation notice on the python py-tree-sitter repository, which advises when speaking about building the libraries:

> This method of loading languages is deprecated and will be removed in v0.22.0. It should only be used for languages that lack updated bindings, and a C compiler will be necessary in those instances.

https://github.com/tree-sitter/py-tree-sitter?tab=readme-ov-file#build-from-source

Any insights you can share would be greatly appreciated

**Comment by gruebel** [comment]
hey @segevfiner I think you forgot to also update `tree-sitter` in the `Cargo.toml`

```rust
[dependencies]
tree-sitter = "~0.20.10" -> "~0.21.0"
```

**Comment by amaanq** [comment]
superseded by #294

**Pull request closed without merging**
